---
# sub_chkp/__dev1_create_checkpoint_gw_bash.yml
#...............................................................
# * taking advantage of bash *
#   ------------------------
#   this playbook would
#     - run 'dev1_create_chkp_gw.sh' on the SMS to
#          > create the gateway object on the SMS database
#...............................................................

- hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - name: Wait up to 300 seconds for SIC port 18211 to Open
    wait_for:
      port: 18211
      host: 10.1.1.1
      delay: 10
    connection: local

- hosts: 10.1.1.101
  gather_facts: no
  connection: local

  tasks:
  - name: "Running scripts/gaia/dev1_create_chkp_gw.sh on 10.1.1.101"
    script: /home/apiadmin/ansible_dev/checkpoint/scripts/gaia/dev1_create_chkp_gw.sh
    register: output

  - debug: var=output.stdout_lines
