---
# file: roles/0_1__add_ssh_key/tasks/main.yml
- name: "waiting up to 120 seconds for ssh port 22 to open on '{{ server_address }}'"
  wait_for:
    port: 22
    host: "{{ server_address }}"
    delay: 10
    timeout: 120
  connection: local

- name: "removing ssh fingerprint of '{{ server_address }}', if it exists in 'known_hosts'"
  command: ssh-keygen -R "{{ server_address }}"
  ignore_errors: yes

- name: "fetching '{{ server_address }}' ssh key "
  command: ssh-keyscan -H -T5 "{{ server_address }}"
  register: keyscan
  failed_when: keyscan.rc != 0 or keyscan.stdout == ''
  changed_when: False
- debug:
    msg: "{{ keyscan.stdout }}"

- pause:
    prompt: "(WARNING):: should the above ssh key be added to 'known_hosts'? (yes/no)"
    echo: yes
  register: result

- name: "adding '{{ server_address }}' ssh-key to local 'known_hosts'"
  lineinfile:
    name: ~/.ssh/known_hosts
#   create: yes
    line: "{{ item }}"
  when: result.user_input == "yes"
  with_items: '{{ keyscan.stdout_lines|default([]) }}'
